// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/type.proto

package typespb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	Unix                 int64    `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_ace1d27388c7352a, []int{0}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (dst *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(dst, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetUnix() int64 {
	if m != nil {
		return m.Unix
	}
	return 0
}

func (m *Timestamp) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "types.Timestamp")
}

func init() { proto.RegisterFile("types/type.proto", fileDescriptor_type_ace1d27388c7352a) }

var fileDescriptor_type_ace1d27388c7352a = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x07, 0x91, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x11, 0x25, 0x53,
	0x2e, 0xce, 0x90, 0xcc, 0xdc, 0xd4, 0xe2, 0x92, 0xc4, 0xdc, 0x02, 0x21, 0x21, 0x2e, 0x96, 0xd2,
	0xbc, 0xcc, 0x0a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0xb5,
	0x2c, 0x31, 0x27, 0x33, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x23, 0x08, 0xc2, 0x71, 0x52, 0xe2,
	0xe2, 0x4c, 0xce, 0xcf, 0xd5, 0x03, 0x9b, 0xe1, 0xc4, 0x15, 0x02, 0xa2, 0x02, 0x40, 0xc6, 0x06,
	0x30, 0x46, 0xb1, 0x83, 0x05, 0x0b, 0x92, 0x92, 0xd8, 0xc0, 0x16, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0xb3, 0x79, 0xd9, 0x7c, 0x00, 0x00, 0x00,
}
