// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/type.proto

package typespb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	Unix                 int64    `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_78c62200ed4d280b, []int{0}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (dst *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(dst, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetUnix() int64 {
	if m != nil {
		return m.Unix
	}
	return 0
}

func (m *Timestamp) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type JSONArray struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSONArray) Reset()         { *m = JSONArray{} }
func (m *JSONArray) String() string { return proto.CompactTextString(m) }
func (*JSONArray) ProtoMessage()    {}
func (*JSONArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_78c62200ed4d280b, []int{1}
}
func (m *JSONArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONArray.Unmarshal(m, b)
}
func (m *JSONArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONArray.Marshal(b, m, deterministic)
}
func (dst *JSONArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONArray.Merge(dst, src)
}
func (m *JSONArray) XXX_Size() int {
	return xxx_messageInfo_JSONArray.Size(m)
}
func (m *JSONArray) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONArray.DiscardUnknown(m)
}

var xxx_messageInfo_JSONArray proto.InternalMessageInfo

func (m *JSONArray) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type JSONMap struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JSONMap) Reset()         { *m = JSONMap{} }
func (m *JSONMap) String() string { return proto.CompactTextString(m) }
func (*JSONMap) ProtoMessage()    {}
func (*JSONMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_78c62200ed4d280b, []int{2}
}
func (m *JSONMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONMap.Unmarshal(m, b)
}
func (m *JSONMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONMap.Marshal(b, m, deterministic)
}
func (dst *JSONMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONMap.Merge(dst, src)
}
func (m *JSONMap) XXX_Size() int {
	return xxx_messageInfo_JSONMap.Size(m)
}
func (m *JSONMap) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONMap.DiscardUnknown(m)
}

var xxx_messageInfo_JSONMap proto.InternalMessageInfo

func (m *JSONMap) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type NullString struct {
	String_              string   `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullString) Reset()         { *m = NullString{} }
func (m *NullString) String() string { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()    {}
func (*NullString) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_78c62200ed4d280b, []int{3}
}
func (m *NullString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullString.Unmarshal(m, b)
}
func (m *NullString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullString.Marshal(b, m, deterministic)
}
func (dst *NullString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullString.Merge(dst, src)
}
func (m *NullString) XXX_Size() int {
	return xxx_messageInfo_NullString.Size(m)
}
func (m *NullString) XXX_DiscardUnknown() {
	xxx_messageInfo_NullString.DiscardUnknown(m)
}

var xxx_messageInfo_NullString proto.InternalMessageInfo

func (m *NullString) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *NullString) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "types.Timestamp")
	proto.RegisterType((*JSONArray)(nil), "types.JSONArray")
	proto.RegisterType((*JSONMap)(nil), "types.JSONMap")
	proto.RegisterMapType((map[string]string)(nil), "types.JSONMap.DataEntry")
	proto.RegisterType((*NullString)(nil), "types.NullString")
}

func init() { proto.RegisterFile("types/type.proto", fileDescriptor_type_78c62200ed4d280b) }

var fileDescriptor_type_78c62200ed4d280b = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xc6, 0xb6, 0xce, 0x78, 0x29, 0x8b, 0x48, 0xf0, 0x62, 0xcc, 0x29, 0x07, 0x89,
	0xa0, 0x88, 0xd2, 0x9b, 0x45, 0x2f, 0x82, 0xb5, 0x6c, 0x7b, 0xf2, 0x36, 0x35, 0x8b, 0x04, 0xf3,
	0x67, 0xd9, 0x6c, 0xc4, 0xfd, 0xf6, 0xb2, 0x93, 0x20, 0x1e, 0x7a, 0x59, 0xde, 0x7b, 0xb3, 0x8f,
	0xfd, 0xed, 0xe0, 0xc2, 0x79, 0xa3, 0xbb, 0xeb, 0x70, 0xe6, 0xc6, 0xb6, 0xae, 0x95, 0x53, 0x4e,
	0xd2, 0x3b, 0x84, 0x5d, 0x59, 0xeb, 0xce, 0x51, 0x6d, 0xa4, 0xc4, 0xa3, 0xbe, 0x29, 0x7f, 0x62,
	0x91, 0x88, 0x2c, 0x52, 0xac, 0xe5, 0x29, 0x4e, 0xbf, 0xa9, 0x2a, 0x8b, 0x78, 0x92, 0x88, 0xec,
	0x58, 0x0d, 0x26, 0xbd, 0x40, 0x78, 0xd9, 0xbe, 0xad, 0x1f, 0xad, 0x25, 0x1f, 0x6a, 0x05, 0x39,
	0x8a, 0x45, 0x12, 0x65, 0xa0, 0x58, 0xa7, 0x06, 0xe7, 0xe1, 0xc2, 0x2b, 0x19, 0x79, 0xf5, 0x6f,
	0x7c, 0x72, 0x13, 0xe7, 0xfc, 0x70, 0x3e, 0x4e, 0xf3, 0x27, 0x72, 0xf4, 0xdc, 0x38, 0xeb, 0x87,
	0xe2, 0xf9, 0x3d, 0xc2, 0x5f, 0x24, 0x17, 0x18, 0x7d, 0x69, 0xcf, 0x3c, 0xa0, 0x82, 0x1c, 0x71,
	0x7a, 0xcd, 0x38, 0xa0, 0x06, 0xb3, 0x9c, 0x3c, 0x88, 0x74, 0x89, 0xb8, 0xee, 0xab, 0x6a, 0xeb,
	0x6c, 0xd9, 0x7c, 0xca, 0x33, 0x9c, 0x75, 0xac, 0xc6, 0xf2, 0xe8, 0x0e, 0x7f, 0x67, 0x75, 0x89,
	0xf0, 0xd1, 0xd6, 0x03, 0xd9, 0x0a, 0x76, 0xde, 0xe8, 0x4d, 0x58, 0xd2, 0x46, 0xbc, 0xcf, 0x39,
	0x33, 0xfb, 0xfd, 0x8c, 0xd7, 0x76, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x67, 0xa2, 0x8f, 0x2b,
	0x4a, 0x01, 0x00, 0x00,
}
